### ISSUE TITLE
provisioning.xsd and parsing tests

### ISSUE THREAD

**Issue by aloubyansky** [aloubyansky/pm#1]
provisioning.xml is a file which is used by the provisioning tool to produce the target installation which is fully described in the provisioning.xml in terms of feature-packs.

Java class that represents provisioning.xml is org.jboss.provisioning.xml.ProvisioningMetaData. There is also an XML parser for it org.jboss.provisioning.xml.ProvisioningXmlParser.

The actual XSD and the parsing tests are currently missing.

**Comment by ppalaga** [comment]
@aloubyansky I guess that the parser and XSD should

(1) behave consistently with each other and 
(2) should not allow useless documents - such as having no FPs at all?

```
<?xml version="1.0" encoding="UTF-8"?>
<installation xmlns="urn:wildfly:pm-provisioning:1.0">
  <universe name="org.jboss.group1">
  </universe>
</installation>
```

**Comment by ppalaga** [comment]
The present parser allows such documents and I'd change it unless you veto.

**Comment by aloubyansky** [comment]
I wouldn't mind if you changed the parser to not allow empty universe elements. Thanks!
