### ISSUE TITLE
Simplify the pm-provisioning XML schema

### ISSUE THREAD

**Issue by ppalaga** [aloubyansky/pm#27]
The present pm-provisioning XML schema prescribes a structure like this:

```
<installation xmlns="urn:wildfly:pm-provisioning:1.0">
  <universe name="org.jboss.group1">
    <feature-pack name="fp1" version="0.0.1" />
    <feature-pack name="fp2" version="0.0.2" />
  </universe>
  <universe name="org.jboss.group2">
    <feature-pack name="fp3" version="0.0.3" />
  </universe>
</installation>
```

I do not find the `universe` element useful in any way and I propose to change the schema so that the structure looks like this:

```
<installation xmlns="urn:wildfly:pm-provisioning:1.0">
    <feature-pack groupId="org.jboss.group1" artifactId="fp1" version="0.0.1" />
    <feature-pack groupId="org.jboss.group1" artifactId="fp2" version="0.0.2" />
    <feature-pack groupId="org.jboss.group2" artifactId="fp3" version="0.0.3" />
</installation>
```

Why:
- Such a flat structure is easier to work with: copy&paste among XML files
- `groupId` and `artifactId` depict better, what those values are
- Neither there is any `universe` grouping in `ProvisionedInstallationDescription`.
- The `server-provisioning.xml` files of `wildfly-server-provisioning-maven-plugin` used exactly this `<feature-pack groupId="org.jboss.group1" artifactId="fp1" version="0.0.1" />` structure. Let's say that we could stay backwards compatible here.

I am ready to perform the necessary changes.

@aloubyansky could you please comment?

**Comment by aloubyansky** [comment]
I guess I wouldn't mind removing the universe from the schema. The reason I added it was that it was present in our design doc. But we could leave it to the user interface only.

BTW, there is not going to be any backward compatibility, so there is no reason to worry about it.

@ppalaga go ahead if you like. Thanks!
