### ISSUE TITLE
provisioned-state.xml marshalling tests

### ISSUE THREAD

**Issue by aloubyansky** [aloubyansky/pm#34]
org.jboss.provisioning.xml.ProvisionedStateXmlWriter takes an instance of org.jboss.provisioning.state.FeaturePackSet<?> and produces an XML representation of the object.

This needs to be covered with the tests.

**Comment by TomasHofman** [comment]
I will work on this one.

**Comment by aloubyansky** [comment]
@TomasHofman thanks! I've updated the description above with the API which is currently in use.
The task is about creating various instances of the org.jboss.provisioning.state.ProvisionedState and marshalling them.

**Comment by TomasHofman** [comment]
@aloubyansky thanks, now it fits :).

I'm only playing around yet, but I noticed that `pm-provisioned-state-1_0.xsd` only allows for `<feature-pack>` elements inside the `<installation>` element, but the `ProvisionedStateBuilder` and the writer allow to add `ProvisionedFeaturePack` _and_ `ProvisionedConfig` objects.

I suspect that the builder is correct and the XSD needs an update? (I will do that, just wanted to check first.)

**Comment by TomasHofman** [comment]
One more question - in general, should writer fail when writing invalid configuration? E.g. ProvisionedState that doesn't contain any FeaturePack, or an incomplete GAV, which would result in non-compliant XML file?

**Comment by aloubyansky** [comment]
@TomasHofman thanks for looking into all this. Yes, the builder is correct and the XSDs may be a bit behind. Will be great to update them.

I'm not sure how you feel about messing with the XSDs but they could be re-structured. By that I mean there are common parts that appear in multiple schemas. E.g. things related to package dependencies (basically the packages element) may appear in a feature spec, in a feature-group spec, in a config, in a feature-pack spec in the provisioning.xml, feature-groups and configs may appear in the feature-pack xml and in the provisioning.xml, feature-pack config may appear in the provisioning.xml and in the feature-pack spec (as fp dependencies). The Java parsers and writers actually do use the same code to parse and write but schemas are duplicating these. I've been thinking about doing something about it. Just in case you feel like looking into this.

In general, I guess, the writer should fail if the model has a problem. But I wouldn't go too deep into this since the model is the product of the mechanism in case it succeeded which assumes that it did already verify everything necessary. Parsing could be more strict on the other hand.
ProvisionedState that does not contain any feature-pack might still be ok. It could be that I installed something and then uninstalled everything. The state would reflect that nothing is installed.

Thanks!

**Comment by TomasHofman** [comment]
I need to analyse those XSDs more deeply, but one thing that occurred to me is that if we wanted to share common parts between them, those common parts would probably need to have their own namespaces, so we would end up mixing multiple namespaces in the top level schemata. Not a problem as such, just something to consider.

**Comment by aloubyansky** [comment]
Yeah, this is not cool. Or we have to keep them all under one namespace.

**Comment by TomasHofman** [comment]
PR with a working version: https://github.com/aloubyansky/pm/pull/190

ProvisionedConfigBuilder allows to add ProvisionedFeature, but the writer doesn't marshal those. I'm not sure if that is intentional. I tried to implement ProvisionedConfigBuilder#handle to fix that.

Is it possible that `configType` in provisioned-state.xsd might be little different from `configType` in e.g. feature-pack.xsd? From the API it looks like in provisioned-state shouldn't allow `feature-pack` and `feature-group` elements, when compared to the one in feature-pack.

BTW after my changes the provisioned state writer produces something like this:

```
<installation xmlns="urn:wildfly:pm-provisioned-state:1.0">
    <feature-pack groupId="org.jboss.group1" artifactId="fp1" version="1.0.0">
        <packages>
            <package name="package1"/>
            <package name="package2"/>
        </packages>
    </feature-pack>
    <feature-pack groupId="org.jboss.group1" artifactId="fp2" version="1.0.0">
        <packages>
            <package name="package3"/>
        </packages>
    </feature-pack>
    <config name="name" model="model">
        <props>
            <prop name="prop2" value="value2"/>
            <prop name="prop" value="value"/>
        </props>
        <feature-pack groupId="org.jboss.group" artifactId="feature1" version="1.0">
            <spec name="spec1">
                <feature id="org.jboss.group:feature1:1.0#spec1:create param=value">
                    <param name="resolved param2" value="value"/>
                    <param name="resolved param" value="value"/>
                    <param name="create param" value="value"/>
                    <param name="param" value="value"/>
                    <param name="param2" value="resolved"/>
                </feature>
            </spec>
        </feature-pack>
        <feature-pack groupId="org.jboss.group" artifactId="spec1" version="1.0">
            <spec name="spec2">
                <feature id="org.jboss.group:spec1:1.0#spec2:id param=value,id param2=resolved">
                    <param name="id param" value="value"/>
                    <param name="id param2" value="resolved"/>
                </feature>
            </spec>
        </feature-pack>
    </config>
    <config/>
</installation>
```

**Comment by aloubyansky** [comment]
That's a good start, thanks! I added comments to the PR. ProvisionedConfigBuilder was not used for persisting the state, so it didn't implement the handle method.

Provisioned state is different from the rest of the metadata (i.e. XxxSpec and XxxConfig classes) in that the provisioned state is the final resolved state (when the spec and config are more like the data and the instructions how to customize the stuff). The resolved (provisioned) config is not more than a set props and a list of features (the order is important) and their resolved parameters. There are no feature-groups, as you noticed.
Also there won't be model-only configs (configs with only the model attribute initialized). Only anonymous (no name, no model) and named configs will appear in the provisioned state.

Thanks again!

**Comment by aloubyansky** [comment]
Thanks Tomas!
